In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
dataset = pd.read_csv("D:/survey lung cancer1.csv")
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [7]:
dataset.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1   69        1               2        2              1   
1       1   74        2               1        1              1   
2       0   59        1               1        1              2   
3       1   63        2               2        2              1   
4       0   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  Level  
0                    2                      2           2      1  
1                    2                      2           2      1  
2                    2                      1           2      0  
3                    1                      2           2      0  
4                    2                      1           1      0

In [8]:
dataset.shape

(309, 16)

In [9]:
dataset.info

<bound method DataFrame.info of      GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         1   69        1               2        2              1   
1         1   74        2               1        1              1   
2         0   59        1               1        1              2   
3         1   63        2               2        2              1   
4         0   63        1               2        1              1   
..      ...  ...      ...             ...      ...            ...   
304       0   56        1               1        1              2   
305       1   70        2               1        1              1   
306       1   58        2               1        1              1   
307       1   67        2               1        2              1   
308       1   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [11]:
X_train.shape

(231, 15)

In [12]:
X_test[:24]

array([[ 0, 68,  1,  1,  2,  1,  2,  1,  2,  2,  2,  1,  1,  2,  1],
       [ 1, 64,  2,  2,  2,  2,  1,  2,  2,  1,  2,  2,  2,  1,  2],
       [ 1, 62,  1,  1,  1,  1,  2,  1,  2,  1,  2,  2,  2,  2,  2],
       [ 1, 68,  1,  1,  2,  2,  2,  1,  1,  1,  2,  1,  1,  1,  1],
       [ 0, 67,  2,  2,  2,  2,  1,  2,  1,  1,  1,  1,  1,  1,  1],
       [ 0, 65,  2,  2,  2,  2,  1,  2,  1,  2,  1,  2,  2,  2,  1],
       [ 0, 55,  2,  2,  2,  2,  2,  2,  1,  2,  1,  2,  2,  2,  1],
       [ 0, 71,  2,  2,  2,  2,  2,  2,  1,  2,  1,  2,  1,  2,  2],
       [ 0, 61,  2,  2,  2,  1,  1,  2,  2,  1,  2,  1,  2,  2,  2],
       [ 0, 56,  1,  2,  1,  1,  2,  2,  2,  2,  1,  2,  2,  1,  2],
       [ 1, 64,  1,  2,  2,  2,  1,  1,  2,  1,  2,  1,  1,  2,  2],
       [ 0, 62,  1,  1,  1,  2,  1,  1,  1,  2,  2,  1,  1,  2,  2],
       [ 0, 56,  2,  2,  2,  1,  1,  2,  2,  1,  1,  1,  2,  1,  2],
       [ 1, 52,  1,  2,  2,  1,  2,  1,  2,  2,  2,  2,  1,  2,  1],
       [ 0, 21,  2,  1,  1,  1,  2

In [13]:
print(Y_train)

[1 0 0 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1
 1 0 1 1 1 0 0 1 1 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1]


In [14]:
print(Y_test)

[1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [16]:
print(X_train[0:10])

[[-1.02188443 -0.2500683   0.91287093  0.85081173  1.04880885  0.99568033
   0.9617692   0.71400555 -1.07651219 -1.18585412 -1.12459143 -1.20724762
   0.72787453  1.04880885 -1.12459143]
 [ 0.97858424 -1.02544785 -1.09544512  0.85081173 -0.95346259 -1.00433842
  -1.03975049  0.71400555 -1.07651219  0.84327404  0.88921183  0.82833048
   0.72787453 -0.95346259 -1.12459143]
 [ 0.97858424  0.7837711   0.91287093 -1.17534816 -0.95346259  0.99568033
  -1.03975049 -1.40054934 -1.07651219 -1.18585412 -1.12459143 -1.20724762
  -1.37386317 -0.95346259  0.88921183]
 [-1.02188443 -2.44697702  0.91287093  0.85081173  1.04880885  0.99568033
   0.9617692   0.71400555 -1.07651219 -1.18585412 -1.12459143 -1.20724762
   0.72787453  1.04880885 -1.12459143]
 [ 0.97858424 -0.12083837  0.91287093  0.85081173 -0.95346259 -1.00433842
   0.9617692  -1.40054934  0.92892585 -1.18585412 -1.12459143  0.82833048
   0.72787453  1.04880885  0.88921183]
 [ 0.97858424 -0.50852815 -1.09544512 -1.17534816 -0.95346259  0.

In [17]:
print(X_test[0:24])

[[-1.13759292  0.6503849  -1.26491106 -1.08012345  0.87904907 -1.
   1.08012345 -1.54638428  0.79056942  1.05266714  0.90219371 -1.08012345
  -1.23131192  1.10840941 -1.10840941]
 [ 0.87904907  0.22408219  0.79056942  0.9258201   0.87904907  1.
  -0.9258201   0.64666979  0.79056942 -0.94996791  0.90219371  0.9258201
   0.8121419  -0.90219371  0.90219371]
 [ 0.87904907  0.01093084 -1.26491106 -1.08012345 -1.13759292 -1.
   1.08012345 -1.54638428  0.79056942 -0.94996791  0.90219371  0.9258201
   0.8121419   1.10840941  0.90219371]
 [ 0.87904907  0.6503849  -1.26491106 -1.08012345  0.87904907  1.
   1.08012345 -1.54638428 -1.26491106 -0.94996791  0.90219371 -1.08012345
  -1.23131192 -0.90219371 -1.10840941]
 [-1.13759292  0.54380923  0.79056942  0.9258201   0.87904907  1.
  -0.9258201   0.64666979 -1.26491106 -0.94996791 -1.10840941 -1.08012345
  -1.23131192 -0.90219371 -1.10840941]
 [-1.13759292  0.33065787  0.79056942  0.9258201   0.87904907  1.
  -0.9258201   0.64666979 -1.26491106  1.

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20, criterion = "entropy", random_state=0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=20, random_state=0)

In [23]:
print(classifier.predict(sc.transform([[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])))

[0]


In [24]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, Y_pred))
#print(classification_report(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))

[[ 6  4]
 [ 4 64]]
0.8974358974358975


In [35]:
def save_trees_as_png(clf, iteration, feature_name, target_name):
    file_name = "Level_" + str(iteration) + ".png"
    dot_data = export_graphviz(
    clf,
    out_file=None,
    feature_names=feature_name,
    #Class_names=target_name,
    rounded=True,
    proportion=False,
    precision=2,
    filled=True,
    )
    graph = pydotplus.graphviz.graph_from_dot_data(dot_data)
    graph.write_png(file_name)
    print("Decision Tree {} saved as png file".format(iteration +1))

In [36]:
classifier.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=209652396),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=398764591),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=924231285),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1478610112),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=441365315),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1537364731),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=192771779),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1491434855),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
           

In [32]:
classifier.estimators_[0]

DecisionTreeClassifier(criterion='entropy', max_features='auto',
                       random_state=209652396)